### ISSUE TITLE
Tests and Debugs

### ISSUE THREAD

**Issue by yyLeaves** [yyLeaves/DS-Project#4]
# Tests

| Part      | Tester1 | Tester2 |
| --------- | ------- | ------- |
| Event 1&2 |     T    |  N       |
| Event 3   | L        |    C     |
| Event 4   |     C    |      N   |
| Event 5   |   L      |     C    |
| Event 6   |     L    |     T    |
| Event 0   |    T     |   N      |

# TODO tests

## L

- [x] Own part &  with GUI part
- [x] event 3
- [x]  5
- [x]  6

## N

- [x] Own part &  with GUI part
- [x] 0
- [x] 1,2
- [x] 4

## T

- [x] Own part &  with GUI part
- [x] 1,2
- [x] 6
- [x] 0

## C

- [x] Own part &  with GUI part
- [x] 3
- [x] 4
- [x] 5

**Comment by yyLeaves** [comment]
I have tested event 3

**Comment by jeongie** [comment]
event 3 
"Each person that had lunch with you will increase your rep with them by 1 point."
Is it suppose to increase the rep at the relationship? 

testing on _9/6 2pm_ shows no change

**Comment by Koukotsukan** [comment]
> event 3
> "Each person that had lunch with you will increase your rep with them by 1 point."
> Is it suppose to increase the rep at the relationship?
> 
> testing on _9/6 2pm_ shows no change

@yyLeaves BTW ```findMaxSolution()``` method returns the ArrayList containing those students who can have lunch with ME.

**Comment by yyLeaves** [comment]
> > event 3
> > "Each person that had lunch with you will increase your rep with them by 1 point."
> > Is it suppose to increase the rep at the relationship?
> > testing on _9/6 2pm_ shows no change
> 
> @yyLeaves BTW `findMaxSolution()` method returns the ArrayList containing those students who can have lunch with ME.

@Koukotsukan Hi, I think it's better to implement it in your methods.

**Comment by Koukotsukan** [comment]
> > > event 3
> > > "Each person that had lunch with you will increase your rep with them by 1 point."
> > > Is it suppose to increase the rep at the relationship?
> > > testing on _9/6 2pm_ shows no change
> > 
> > 
> > @yyLeaves BTW `findMaxSolution()` method returns the ArrayList containing those students who can have lunch with ME.
> 
> @Koukotsukan Hi, I think it's better to implement it in your methods.

ok

**Comment by Koukotsukan** [comment]
> 
> 
> event 3
> "Each person that had lunch with you will increase your rep with them by 1 point."
> Is it suppose to increase the rep at the relationship?
> 
> testing on _9/6 2pm_ shows no change

https://github.com/yyLeaves/DS-Project/commit/a10b6b4987257b617aa6245585d8bfacd0010455
Hi, the problem has been resolved (at least I think it has). Please check again, thank you.
